I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call show_my_available_protectors(False)
  File "game/training.rpy", line 4, in script
    $ allMissions[0].startMission(selected_protector.name)
  File "game/training.rpy", line 4, in <module>
    $ allMissions[0].startMission(selected_protector.name)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Mission.startMission() missing 1 required positional argument: 'success_rate'

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call show_my_available_protectors(False)
  File "game/training.rpy", line 4, in script
    $ allMissions[0].startMission(selected_protector.name)
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/training.rpy", line 4, in <module>
    $ allMissions[0].startMission(selected_protector.name)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Mission.startMission() missing 1 required positional argument: 'success_rate'

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Tue Aug 19 17:13:18 2025
