I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/functions.rpy", line 9, in script
    init python:
  File "game/functions.rpy", line 60, in <module>
    config.keymap['hide_windows'].remove('h')
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
ValueError: list.remove(x): x not in list

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/functions.rpy", line 9, in script
    init python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/functions.rpy", line 60, in <module>
    config.keymap['hide_windows'].remove('h')
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/common/00keymap.rpy", line 28, in remove
    _list.remove(self, a)
    ~~~~~~~~~~~~^^^^^^^^^
ValueError: list.remove(x): x not in list

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Fri Aug  8 10:56:21 2025
