I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 11, in script call
    call check_online_shop()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 11, in script call
    call check_online_shop()
renpy.script.LabelNotFound: could not find label 'check_online_shop'.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 11, in script call
    call check_online_shop()
  File "renpy/ast.py", line 1622, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 11, in script call
    call check_online_shop()
  File "renpy/script.py", line 1161, in lookup
    raise LabelNotFound(original)
renpy.script.LabelNotFound: could not find label 'check_online_shop'.

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Mon Aug 11 22:36:20 2025
