I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    $ initializing_things()
  File "game/script.rpy", line 60, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 3117, in initializing_things
    myWeapons.append(next(w for w in weapons if w.weapon_id == 15))
                     ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
StopIteration

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 60, in script
    $ initializing_things()
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 60, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 3117, in initializing_things
    myWeapons.append(next(w for w in weapons if w.weapon_id == 15))
                     ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
StopIteration

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Sun Aug 31 14:00:31 2025
