I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 205, in script
    $ update_protector_weapon(first_protector_selected, "Thieves knife")
  File "game/script.rpy", line 205, in <module>
    $ update_protector_weapon(first_protector_selected, "Thieves knife")
      ^^^^^^^^^^^^^^^^^^^^^^^                                           
NameError: name 'update_protector_weapon' is not defined

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 205, in script
    $ update_protector_weapon(first_protector_selected, "Thieves knife")
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 205, in <module>
    $ update_protector_weapon(first_protector_selected, "Thieves knife")
      ^^^^^^^^^^^^^^^^^^^^^^^                                           
NameError: name 'update_protector_weapon' is not defined

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Fri Aug  8 16:59:10 2025
