I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    $ initializing_things()
  File "game/script.rpy", line 60, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 2438, in initializing_things
    myWeapons.append(adding_weapon)
                     ^^^^^^^^^^^^^ 
NameError: name 'adding_weapon' is not defined

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 60, in script
    $ initializing_things()
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 60, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 2438, in initializing_things
    myWeapons.append(adding_weapon)
                     ^^^^^^^^^^^^^ 
NameError: name 'adding_weapon' is not defined

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Tue Sep  2 13:40:46 2025
