I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    $ initializing_things()
  File "game/script.rpy", line 29, in <module>
    $ initializing_things()
  File "game/functions.rpy", line 261, in initializing_things
    allMissions.append(Mission("Training", "Send a protector to train in your facilities.", 0, 1, 1, "Training", "not assigned", 1900, 0))
  File "game/classes.rpy", line 108, in __init__
    self.daysPassed
AttributeError: 'Mission' object has no attribute 'daysPassed'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script
    $ initializing_things()
  File "D:\renpy\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 29, in <module>
    $ initializing_things()
  File "game/functions.rpy", line 261, in initializing_things
    allMissions.append(Mission("Training", "Send a protector to train in your facilities.", 0, 1, 1, "Training", "not assigned", 1900, 0))
  File "game/classes.rpy", line 108, in __init__
    self.daysPassed
AttributeError: 'Mission' object has no attribute 'daysPassed'

Windows-10-10.0.26120 AMD64
Ren'Py 8.3.7.25031702
Protectors 1.0
Mon Aug  4 23:00:09 2025
