I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 15, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/training.rpy", line 4, in script
    $ allExpeditions[0].startExpedition()
  File "game/training.rpy", line 4, in <module>
    $ allExpeditions[0].startExpedition()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 605, in startExpedition
    my_protector.set_status("In a mission")
    ^^^^^^^^^^^^^^^^^^^^^^^                
AttributeError: 'NoneType' object has no attribute 'set_status'

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 15, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/training.rpy", line 4, in script
    $ allExpeditions[0].startExpedition()
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/training.rpy", line 4, in <module>
    $ allExpeditions[0].startExpedition()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 605, in startExpedition
    my_protector.set_status("In a mission")
    ^^^^^^^^^^^^^^^^^^^^^^^                
AttributeError: 'NoneType' object has no attribute 'set_status'

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Mon Sep 15 18:27:00 2025
